[package]
name = "permscan"
version = "2.1.3"
edition = "2021"
authors = ["Pythack pythackcode@gmail.com"]
[[bin]]
name = "permscan"
path = "./src/main.rs"
[dependencies]
structopt = { version = "0.3.26", default-features = false }
regex = "1.5.5"
itertools = "0.10.3"
array_tool = "1.0.3"
