FROM alpine:3.14

LABEL org.opencontainers.image.source="https://github.com/pythack/permscan"

# Add Rust on image

RUN \
    apk update &&\
    apk add rustup &&\
    apk add pkgconfig &&\
    apk add build-base &&\
    rustup-init -y

# Copying the code
WORKDIR /permscan_code/
COPY ./Cargo.toml ./
COPY ./src/ ./src/

RUN source $HOME/.cargo/env &&\
    cargo build --release &&\
    cp ./target/release/permscan /bin

# Making the tar.gz file
RUN \
    mkdir permscan-x86_64-unknown-linux-musl &&\
    mv ./target/release/permscan permscan-x86_64-unknown-linux-musl &&\
    tar -czvf permscan-x86_64-unknown-linux-musl.tar.gz permscan-x86_64-unknown-linux-musl &&\
    rm -rf permscan-x86_64-unknown-linux-musl

WORKDIR /
