FROM rust:latest
LABEL org.opencontainers.image.source="https://github.com/pythack/permscan"

# Copying the code
WORKDIR /permscan_code/
COPY ./Cargo.toml ./
COPY ./src/ ./src/

# Building and installing the binary
RUN \
    cargo build --release &&\
    cp ./target/release/permscan /bin

# Making the tar.gz file
RUN \
    mkdir permscan-x86_64-unknown-linux-gnu &&\
    mv ./target/release/permscan permscan-x86_64-unknown-linux-gnu &&\
    tar -czvf permscan-x86_64-unknown-linux-gnu.tar.gz permscan-x86_64-unknown-linux-gnu &&\
    rm -rf permscan-x86_64-unknown-linux-gnu

WORKDIR /