name: Update Docker Images

on: 
  push:
    branches: [ master ]

jobs:
  publish-permscan-image-gnu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build the permscan Docker image
      run: |
        docker build -f Dockerfile_gnu . --tag ghcr.io/pythack/permscan_gnu:latest
        docker run ghcr.io/pythack/permscan_gnu:latest
    - name: Push the permscan Docker image
      run: docker push ghcr.io/pythack/permscan_gnu:latest
  publish-permscan-image-musl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build the permscan Docker image
      run: |
        docker build -f Dockerfile_musl . --tag ghcr.io/pythack/permscan_musl:latest
        docker run ghcr.io/pythack/permscan_musl:latest
    - name: Push the permscan Docker image
      run: docker push ghcr.io/pythack/permscan_musl:latest
