name: Update Docker Images

on: 
  push:
    branches: [ master ]

jobs:
  publish-permscan-image-gnu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build the permscan Docker image
      run: |
        docker build -f Dockerfile-gnu . --tag ghcr.io/pythack/permscan-gnu:latest
        docker run ghcr.io/pythack/permscan-gnu:latest
    - name: Push the permscan Docker image
      run: docker push ghcr.io/pythack/permscan-gnu:latest
    - uses: actions/delete-package-versions@v3
      with: 
        package-name: 'permscan-gnu'
        min-versions-to-keep: 1
  publish-permscan-image-musl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build the permscan Docker image
      run: |
        docker build -f Dockerfile-musl . --tag ghcr.io/pythack/permscan-musl:latest
        docker run ghcr.io/pythack/permscan-musl:latest
    - name: Push the permscan Docker image
      run: docker push ghcr.io/pythack/permscan-musl:latest
    - uses: actions/delete-package-versions@v3
      with: 
        package-name: 'permscan-musl'
        min-versions-to-keep: 1
