name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-gnu:
    runs-on: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: cargo check --verbose # Checks if it can compile without actually
        # compiling it

  build-musl:
    runs-on:
